// Запрос списка услуг
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';

// Добавление услуг
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_ERROR = 'ADD_SERVICE_ERROR';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';

// Удаление услуг
export const REMOVE_SERVICE_REQUEST = 'REMOVE_SERVICE_REQUEST';
export const REMOVE_SERVICE_ERROR = 'REMOVE_SERVICE_ERROR';
export const REMOVE_SERVICE_SUCCESS = 'REMOVE_SERVICE_SUCCESS';

// Состояние инпутов
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_CHANGE_SERVICE_FIELD = 'EDIT_CHANGE_SERVICE_FIELD';

// Редактирование услуг (GET)
export const FETCH_EDIT_SERVICE_REQUEST = 'FETCH_EDIT_SERVICE_REQUEST';
export const FETCH_EDIT_SERVICE_ERROR = 'FETCH_EDIT_SERVICE_ERROR';
export const FETCH_EDIT_SERVICE_SUCCESS = 'FETCH_EDIT_SERVICE_SUCCESS';

// Редактирование услуг (POST)
export const EDIT_SERVICES_REQUEST = 'EDIT_SERVICES_REQUEST';
export const EDIT_SERVICES_ERROR = 'EDIT_SERVICES_ERROR';
export const EDIT_SERVICES_SUCCESS = 'EDIT_SERVICES_SUCCESS';